name: Build & publish Docker container
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: select tag name
        id: tag_name
        run: if [[ "${GITHUB_REF}" =~ ^refs/tags/.* ]]; then echo ::set-output name=tag::${GITHUB_REF#refs/tags/}; else echo ::set-output name=tag::latest; fi

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: falldamage/lmx-rizomlab:${{steps.tag_name.outputs.tag }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

